Traceback (most recent call last):                                                                                                                                                                          File "analyzer.py", line 138, in <module>                                                                                                                                                                   asyncio.get_event_loop().run_until_complete(main())                                                                                                                                                     File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\asyncio\base_events.py", line 603, in run_until_complete                                                                                            self.run_forever()                                                                                                                                                                                      File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\asyncio\windows_events.py", line 316, in run_forever                                                                                                super().run_forever()                                                                                                                                                                                   File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\asyncio\base_events.py", line 570, in run_forever                                                                                                   self._run_once()                                                                                                                                                                                        File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\asyncio\base_events.py", line 1823, in _run_once                                                                                                    event_list = self._selector.select(timeout)                                                                                                                                                             File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\asyncio\windows_events.py", line 434, in select                                                                                                     self._poll(timeout)                                                                                                                                                                                     File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\asyncio\windows_events.py", line 783, in _poll                                                                                                      status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)                                                                                                                                          File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\site-packages\pyppeteer\launcher.py", line 153, in _close_process                                                                                   self._loop.run_until_complete(self.killChrome())                                                                                                                                                        File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\asyncio\base_events.py", line 592, in run_until_complete                                                                                            self._check_running()                                                                                                                                                                                   File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\asyncio\base_events.py", line 552, in _check_running                                                                                                raise RuntimeError('This event loop is already running')                                                                                                                                              RuntimeError: This event loop is already running                                                                                                                                                          Future exception was never retrieved                                                                                                                                                                      future: <Future finished exception=NetworkError('Protocol error Target.sendMessageToTarget: Target closed.')>                                                                                             pyppeteer.errors.NetworkError: Protocol error Target.sendMessageToTarget: Target closed.                                                                                                                  sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited                                                                                                                                  Task exception was never retrieved                                                                                                                                                                        future: <Task finished name='Task-1' coro=<main() done, defined at analyzer.py:77> exception=NetworkError('Protocol error Emulation.setDeviceMetricsOverride: Target closed.')>                           Traceback (most recent call last):                                                                                                                                                                          File "analyzer.py", line 91, in main                                                                                                                                                                        while True: await page.screenshot({'path': 'example.png', 'fullPage': True})                                                                                                                            File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\site-packages\pyppeteer\page.py", line 1179, in screenshot                                                                                          return await self._screenshotTask(screenshotType, options)                                                                                                                                              File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\site-packages\pyppeteer\page.py", line 1236, in _screenshotTask                                                                                     await self.setViewport(self._viewport)                                                                                                                                                                  File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\site-packages\pyppeteer\page.py", line 1089, in setViewport                                                                                         needsReload = await self._emulationManager.emulateViewport(viewport)                                                                                                                                    File "C:\Users\Bach Nguyen\.conda\envs\study-stream\lib\site-packages\pyppeteer\emulation_manager.py", line 38, in emulateViewport                                                                          await self._client.send('Emulation.setDeviceMetricsOverride', options)                                                                                                                                pyppeteer.errors.NetworkError: Protocol error Emulation.setDeviceMetricsOverride: Target closed.